import {
  LayoutDashboard,
  BedDouble,
  DoorOpen,
  CalendarCheck2,
  Users,
  LogIn,
  LogOut,
  Sparkles,
  UtensilsCrossed,
  Grid2x2,
  BookOpen,
  ShoppingCart,
  Receipt,
  BarChart3,
  Package,
  Tags,
  Truck,
  ShoppingBag,
  ArrowLeftRight,
  AlertTriangle,
  Wallet,
  FileText,
  ReceiptText,
  TrendingUp,
  Calculator,
  Building2,
  UserCog,
  Settings,
  ShieldCheck,
  Bot,
  Menu,
} from 'lucide-react';

export const NAV = [
  { type: 'link', to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  {
    type: 'group',
    label: 'Hotel',
    icon: Building2,
    children: [
      { to: '/rooms', label: 'Rooms', icon: BedDouble },
      { to: '/room-types', label: 'Room Types', icon: DoorOpen },
      { to: '/reservations', label: 'Reservations', icon: CalendarCheck2 },
      { to: '/guests', label: 'Guests', icon: Users },
      { to: '/checkin', label: 'Check-in / Check-out', icon: LogIn },
      { to: '/housekeeping', label: 'Housekeeping', icon: Sparkles },
    ],
  },
  {
    type: 'group',
    label: 'Restaurants',
    icon: UtensilsCrossed,
    children: [
      { to: '/restaurants', label: 'Restaurants', icon: Building2 },
      { to: '/restaurants/tables', label: 'Tables', icon: Grid2x2 },
      { to: '/restaurants/menu', label: 'Menu', icon: BookOpen },
      { to: '/restaurants/pos', label: 'POS', icon: ShoppingCart },
      { to: '/restaurants/orders', label: 'Orders', icon: Receipt },
      { to: '/restaurants/reports', label: 'Restaurant Reports', icon: BarChart3 },
    ],
  },
  {
    type: 'group',
    label: 'Inventory',
    icon: Package,
    children: [
      { to: '/inventory', label: 'Products', icon: Package },
      { to: '/inventory/categories', label: 'Categories', icon: Tags },
      { to: '/inventory/suppliers', label: 'Suppliers', icon: Truck },
      { to: '/inventory/purchases', label: 'Purchases', icon: ShoppingBag },
      { to: '/inventory/movements', label: 'Stock Movement', icon: ArrowLeftRight },
      { to: '/inventory/low-stock', label: 'Low Stock', icon: AlertTriangle },
    ],
  },
  {
    type: 'group',
    label: 'Finance',
    icon: Wallet,
    children: [
      { to: '/finance/payments', label: 'Payments', icon: Wallet },
      { to: '/finance/invoices', label: 'Invoices', icon: FileText },
      { to: '/finance/expenses', label: 'Expenses', icon: ReceiptText },
      { to: '/finance/revenue', label: 'Revenue', icon: TrendingUp },
      { to: '/finance/accounting', label: 'Accounting Reports', icon: Calculator },
    ],
  },
  {
    type: 'group',
    label: 'Reports',
    icon: BarChart3,
    children: [
      { to: '/reports/hotel', label: 'Hotel Reports', icon: BarChart3 },
      { to: '/restaurants/reports', label: 'Restaurant Reports', icon: UtensilsCrossed },
      { to: '/reports/inventory', label: 'Inventory Reports', icon: Package },
      { to: '/reports/financial', label: 'Financial Reports', icon: Calculator },
    ],
  },
  {
    type: 'group',
    label: 'Administration',
    icon: ShieldCheck,
    children: [
      { to: '/admin/staff', label: 'Staff', icon: UserCog },
      { to: '/admin/roles', label: 'Roles & Permissions', icon: ShieldCheck },
      { to: '/admin/settings', label: 'Settings', icon: Settings },
      { to: '/admin/audit', label: 'Audit Logs', icon: Menu },
    ],
  },
  { type: 'link', to: '/ai', label: 'AI Assistant', icon: Bot },
];
