import {
  LayoutDashboard,
  BedDouble,
  DoorOpen,
  CalendarCheck2,
  Users,
  LogIn,
  LogOut,
  Sparkles,
  UtensilsCrossed,
  Grid2x2,
  BookOpen,
  ShoppingCart,
  Receipt,
  BarChart3,
  Package,
  Tags,
  Truck,
  ShoppingBag,
  ArrowLeftRight,
  AlertTriangle,
  Wallet,
  FileText,
  ReceiptText,
  TrendingUp,
  Calculator,
  Percent,
  Building2,
  UserCog,
  Settings,
  ShieldCheck,
  Bot,
  Menu,
  Waves,
  Flower2,
  CalendarClock,
  CalendarDays,
  Wrench,
  HandCoins,
  ClipboardList,
} from 'lucide-react';
import { PERM } from '../../utils/permissions.js';

export const NAV = [
  { type: 'link', to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, perms: [PERM.DASHBOARD] },
  {
    type: 'group',
    label: 'Hotel',
    icon: Building2,
    children: [
      { to: '/rooms', label: 'Rooms', icon: BedDouble, perms: [PERM.ROOMS_VIEW] },
      { to: '/reservations', label: 'Reservations', icon: CalendarCheck2, perms: [PERM.RESERVATIONS_VIEW] },
      { to: '/guests', label: 'Guests', icon: Users, perms: [PERM.GUESTS_VIEW] },
      { to: '/checkin', label: 'Check-in / Check-out', icon: LogIn, perms: [PERM.CHECKIN_VIEW] },
      { to: '/housekeeping', label: 'Housekeeping', icon: Sparkles, perms: [PERM.HOUSEKEEPING_VIEW] },
      { to: '/maintenance', label: 'Maintenance', icon: Wrench, perms: [PERM.MAINTENANCE_VIEW] },
      { to: '/room-types', label: 'Room Types', icon: DoorOpen, perms: [PERM.ROOM_TYPES_MANAGE] },
    ],
  },
  {
    type: 'group',
    label: 'Restaurants',
    icon: UtensilsCrossed,
    children: [
      { to: '/restaurants', label: 'Outlets', icon: Building2, perms: [PERM.RESTAURANTS_MANAGE] },
      { to: '/restaurants/tables', label: 'Tables', icon: Grid2x2, perms: [PERM.TABLES_VIEW] },
      { to: '/restaurants/menu', label: 'Menu', icon: BookOpen, perms: [PERM.MENU_VIEW] },
      { to: '/restaurants/pos', label: 'Sell', icon: ShoppingCart, perms: [PERM.POS_USE] },
      { to: '/restaurants/orders', label: 'Orders', icon: Receipt, perms: [PERM.ORDERS_VIEW] },
      { to: '/restaurants/reports', label: 'Reports', icon: BarChart3, perms: [PERM.RESTAURANT_REPORTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Amenities & Services',
    icon: Sparkles,
    children: [
      { to: '/amenities', label: 'Amenities', icon: Sparkles, perms: [PERM.AMENITIES_VIEW] },
      { to: '/amenities/appointments', label: 'Appointments', icon: CalendarClock, perms: [PERM.APPOINTMENTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Conference & Events',
    icon: CalendarDays,
    children: [
      { to: '/events/halls', label: 'Conference Halls', icon: DoorOpen, perms: [PERM.HALLS_VIEW] },
      { to: '/events', label: 'Events', icon: CalendarDays, perms: [PERM.EVENTS_VIEW] },
      { to: '/events/services', label: 'Event Services', icon: Wrench, perms: [PERM.EVENTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Inventory',
    icon: Package,
    children: [
      { to: '/inventory', label: 'Products', icon: Package, perms: [PERM.INVENTORY_VIEW] },
      { to: '/inventory/categories', label: 'Kinds', icon: Tags, perms: [PERM.CATEGORIES_VIEW] },
      { to: '/inventory/suppliers', label: 'Suppliers', icon: Truck, perms: [PERM.SUPPLIERS_VIEW] },
      { to: '/inventory/purchases', label: 'Purchases', icon: ShoppingBag, perms: [PERM.PURCHASES_VIEW] },
      { to: '/inventory/movements', label: 'Stock in and out', icon: ArrowLeftRight, perms: [PERM.INVENTORY_VIEW] },
      { to: '/inventory/low-stock', label: 'Needs restock', icon: AlertTriangle, perms: [PERM.LOW_STOCK_VIEW] },
      { to: '/purchase-requests', label: 'Ask to buy', icon: ClipboardList, perms: [PERM.PURCHASE_REQUESTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Cashier',
    icon: HandCoins,
    children: [
      { to: '/shifts', label: 'Shifts', icon: HandCoins, perms: [PERM.SHIFTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Finance',
    icon: Wallet,
    children: [
      { to: '/finance/payments', label: 'Payments', icon: Wallet, perms: [PERM.PAYMENTS_VIEW] },
      { to: '/finance/invoices', label: 'Bills', icon: FileText, perms: [PERM.INVOICES_VIEW] },
      { to: '/finance/expenses', label: 'Money out', icon: ReceiptText, perms: [PERM.EXPENSES_VIEW] },
      { to: '/finance/revenue', label: 'Money in', icon: TrendingUp, perms: [PERM.REVENUE_VIEW] },
      { to: '/finance/accounting', label: 'Books', icon: Calculator, perms: [PERM.ACCOUNTING_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Reports',
    icon: BarChart3,
    children: [
      { to: '/reports/kpis', label: 'Hotel numbers', icon: Percent, perms: [PERM.KPIS_VIEW] },
      { to: '/reports/hotel', label: 'Hotel', icon: BarChart3, perms: [PERM.HOTEL_REPORTS_VIEW] },
      { to: '/reports/inventory', label: 'Store', icon: Package, perms: [PERM.INVENTORY_REPORTS_VIEW] },
      { to: '/reports/financial', label: 'Money', icon: Calculator, perms: [PERM.FINANCIAL_REPORTS_VIEW] },
      { to: '/reports/amenities', label: 'Amenities', icon: Sparkles, perms: [PERM.SERVICE_REPORTS_VIEW] },
      { to: '/reports/events', label: 'Events', icon: CalendarDays, perms: [PERM.EVENT_REPORTS_VIEW] },
      { to: '/reports/outlets', label: 'Outlets', icon: UtensilsCrossed, perms: [PERM.RESTAURANT_REPORTS_VIEW] },
      { to: '/reports/combined', label: 'All together', icon: Calculator, perms: [PERM.FINANCIAL_REPORTS_VIEW] },
    ],
  },
  {
    type: 'group',
    label: 'Administration',
    icon: ShieldCheck,
    children: [
      { to: '/admin/staff', label: 'Staff', icon: UserCog, perms: [PERM.STAFF_VIEW] },
      { to: '/admin/roles', label: 'Roles & Permissions', icon: ShieldCheck, perms: [PERM.ROLES_MANAGE] },
      { to: '/admin/settings', label: 'Settings', icon: Settings, perms: [PERM.SETTINGS_MANAGE] },
      { to: '/admin/audit', label: 'Audit Logs', icon: Menu, perms: [PERM.AUDIT_VIEW] },
    ],
  },
  { type: 'link', to: '/ai', label: 'AI Assistant', icon: Bot, perms: [PERM.AI_USE] },
];
